name: build-main

on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

jobs:
  build-main:
    uses: ./.github/workflows/build-reusable.yaml
    with:
      rosdistro: galactic
      branch: ""
